name: After release emqx operator

on:
  release:
    types:
    - released

jobs:
  after-release:
    runs-on: ubuntu-latest
    steps:
    - name: Update operator CI
      run: |
          curl --location --request POST ${{ secrets.EMQX_IO_RELEASE_API }} \
            --header 'token: ${{ secrets.EMQX_IO_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "OperatorVersion": "${{ github.ref_name }}",
                "EmqxVersion": ["4.4.x"]
            }'